ALTERNATE_DIAGNOSES = {
        "ATELECTASIS",
        "PULMONARY_EDEMA",
        # "SOFT_TISSUE_ATTENUATION",
        # "PLEURAL_EFFUSION",
        # "EMPHYSEMA",
        "INTERSTITIAL_LUNG_DISEASE",
        "FIBROSIS",

}

